function Adot = getAdot(param, q, qdot)
%ADOT
%    ADOT = ADOT(DX,DY,DZ,GMA_1,GMA_2,GMA_1DOT,GMA_2DOT,L_1,L_2,PHI_X,PHI_Y,PHI_Z,PHI_XDOT,PHI_YDOT,PHI_ZDOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-May-2021 21:24:32
%% Parameters
% masses
m_B = param.m_B; % multirotor body
m_S1 = param.m_S1; % 1st servo motor (XW540)
m_L1 = param.m_L1; % 1st link
m_S2 = param.m_S2; % 2nd servo motor (XH430)
m_L2 = param.m_L2; % 2nd link
m_S3 = param.m_S3; % 3rd servo motor (XL430-W250-T)
m_E = param.m_E; % end-effector (gripper)

% length
dx = param.dx; % X distance from multirotor c.o.m to 1st servo
dy = param.dy; % Y distance from multirotor c.o.m to 1st servo
dz = param.dz; % Z distance from multirotor c.o.m to 1st servo
l_1 = param.l_1; % 1st link length
l_2 = param.l_2; % 2nd link

% moment of inertia (MOI)
J_Bx = param.J_Bx; J_By = param.J_By; J_Bz = param.J_Bz;
J_S1x = param.J_S1x; J_S1y = param.J_S1y; J_S1z = param.J_S1z;
J_L1x = param.J_L1x; J_L1y = param.J_L1y; J_L1z = param.J_L1z;
J_S2x = param.J_S2x; J_S2y = param.J_S2y; J_S2z = param.J_S2z;
J_L2x = param.J_L2x; J_L2y = param.J_L2y; J_L2z = param.J_L2z;
J_S3x = param.J_S3x; J_S3y = param.J_S3y; J_S3z = param.J_S3z;
J_Ex = param.J_Ex; J_Ey = param.J_Ey; J_Ez = param.J_Ez;

% etc
g = param.g; % gravitational acceleration [m/s^2]

%% State distribution
p_x = q(1);
p_y = q(2);
p_z = q(3);
phi_x = q(4);
phi_y = q(5);
phi_z = q(6);
gma_1 = q(7);
gma_2 = q(8);
p_xdot = qdot(1);
p_ydot = qdot(2);
p_zdot = qdot(3);
phi_xdot = qdot(4);
phi_ydot = qdot(5);
phi_zdot = qdot(6);
gma_1dot = qdot(7);
gma_2dot = qdot(8);

%%
t2 = cos(gma_1);
t3 = cos(phi_x);
t4 = cos(phi_y);
t5 = cos(phi_z);
t6 = sin(gma_1);
t7 = sin(phi_x);
t8 = sin(phi_y);
t9 = sin(phi_z);
t10 = gma_1+gma_2;
t11 = cos(t10);
t12 = l_1.*t2;
t13 = sin(t10);
t14 = l_1.*t6;
t15 = t3.*t5;
t16 = t3.*t9;
t17 = t5.*t7;
t18 = t7.*t9;
t21 = dy.*t3.*t8;
t22 = dy.*t4.*t7;
t19 = l_2.*t11;
t20 = l_2.*t13;
t23 = t8.*t18;
t24 = t8.*t15;
t25 = t8.*t16;
t26 = t8.*t17;
t28 = dy.*t4.*t15;
t29 = dy.*t4.*t16;
t30 = dy.*t4.*t17;
t32 = dy.*t4.*t18;
t27 = t4.*t19;
t31 = t8.*t20;
t33 = -t25;
t34 = -t26;
t38 = t5.*t8.*t19;
t39 = t4.*t5.*t20;
t41 = t8.*t9.*t19;
t42 = t4.*t9.*t20;
t43 = t12+t19;
t44 = t14+t20;
t51 = t4.*t15.*t20;
t52 = t4.*t16.*t20;
t53 = t15+t23;
t54 = t18+t24;
t35 = t3.*t27;
t36 = t5.*t27;
t37 = t9.*t27;
t40 = t3.*t31;
t48 = -t42;
t49 = dz+t43;
t50 = dx+t44;
t55 = t4.*t43;
t56 = dy.*t53;
t57 = dy.*t54;
t58 = t16+t34;
t59 = t17+t33;
t62 = t5.*t8.*t43;
t63 = t8.*t9.*t43;
t64 = t3.*t8.*t44;
t73 = t4.*t15.*t44;
t75 = t4.*t16.*t44;
t81 = t19.*t54;
t82 = t20.*t54;
t92 = t38+t51;
t94 = t41+t52;
t95 = t44.*t54;
t45 = -t35;
t46 = -t36;
t47 = -t40;
t60 = t5.*t55;
t61 = t9.*t55;
t65 = dy.*t58;
t66 = dy.*t59;
t67 = t3.*t4.*t49;
t68 = t4.*t5.*t50;
t69 = t7.*t8.*t49;
t70 = t4.*t9.*t50;
t71 = t5.*t8.*t50;
t72 = t8.*t9.*t50;
t76 = -t64;
t77 = t4.*t15.*t49;
t78 = t4.*t16.*t49;
t79 = t4.*t17.*t49;
t80 = t4.*t18.*t49;
t90 = t19.*t59;
t91 = t20.*t59;
t96 = t49.*t53;
t97 = t49.*t54;
t99 = t44.*t59;
t100 = t49.*t58;
t101 = t49.*t59;
t103 = t39+t81;
t112 = t62+t73;
t113 = t63+t75;
t74 = -t60;
t83 = -t69;
t84 = -t71;
t85 = -t72;
t86 = -t79;
t87 = -t80;
t88 = t27+t47;
t89 = t31+t45;
t105 = -t101;
t106 = gma_2dot.*t103;
t107 = t46+t82;
t108 = t37+t91;
t109 = t55+t76;
t111 = t48+t90;
t114 = -gma_2dot.*(t42-t90);
t115 = t61+t99;
t116 = t57+t100;
t117 = t66+t96;
t93 = gma_2dot.*t89;
t98 = t21+t83;
t102 = t28+t86;
t104 = t29+t87;
t110 = -t106;
t118 = t74+t95;
t119 = t30+t77+t84;
t120 = t32+t78+t85;
Adot = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,phi_ydot.*t102+phi_zdot.*t117+phi_xdot.*(t65-t97)-gma_2dot.*t20.*t58-gma_1dot.*t44.*t58,-phi_xdot.*(t56+t105)+phi_ydot.*t104+phi_zdot.*t116+gma_2dot.*t20.*t53+gma_1dot.*t44.*t53,-phi_xdot.*(t22+t67)-phi_ydot.*t98+gma_2dot.*t4.*t7.*t20+gma_1dot.*t4.*t7.*t44,-phi_ydot.*(t68+dy.*t26+t24.*t49)-gma_2dot.*t92-gma_1dot.*t112+phi_xdot.*t102-phi_zdot.*t120,-phi_ydot.*(t70+dy.*t23+t25.*t49)-gma_2dot.*t94-gma_1dot.*t113+phi_xdot.*t104+phi_zdot.*t119,-gma_2dot.*t88-gma_1dot.*t109-phi_xdot.*t98-phi_ydot.*(t22+t67-t8.*t50),-gma_2dot.*t108-gma_1dot.*t115+phi_xdot.*t117-phi_ydot.*t120-phi_zdot.*(-t65+t68+t97),phi_xdot.*t116+phi_ydot.*t119+gma_2dot.*(t36-t82)+gma_1dot.*(t60-t95)-phi_zdot.*(t56+t70+t105),0.0,t110-gma_1dot.*(t43.*t54+t4.*t5.*t44)-phi_ydot.*t112-phi_zdot.*t115-phi_xdot.*t44.*t58,t114+gma_1dot.*(t43.*t59-t4.*t9.*t44)-phi_ydot.*t113+phi_zdot.*(t60-t95)+phi_xdot.*t44.*t53,t93-phi_ydot.*t109+gma_1dot.*(t8.*t44-t3.*t55)+phi_xdot.*t4.*t7.*t44,t110-gma_1dot.*t103-phi_ydot.*t92-phi_zdot.*t108-phi_xdot.*t20.*t58,t114-phi_ydot.*t94-gma_1dot.*(t42-t90)+phi_zdot.*(t36-t82)+phi_xdot.*t20.*t53,t93+gma_1dot.*t89-phi_ydot.*t88+phi_xdot.*t4.*t7.*t20],[3,8]);
