function G = getG(param, q)
%G
%    G = G(DX,DY,DZ,G,GMA_1,GMA_2,L_1,L_2,M_B,M_E,M_L1,M_L2,M_S1,M_S2,M_S3,PHI_X,PHI_Y)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-May-2021 21:24:30
%% Parameters
% masses
m_B = param.m_B; % multirotor body
m_S1 = param.m_S1; % 1st servo motor (XW540)
m_L1 = param.m_L1; % 1st link
m_S2 = param.m_S2; % 2nd servo motor (XH430)
m_L2 = param.m_L2; % 2nd link
m_S3 = param.m_S3; % 3rd servo motor (XL430-W250-T)
m_E = param.m_E; % end-effector (gripper)

% length
dx = param.dx; % X distance from multirotor c.o.m to 1st servo
dy = param.dy; % Y distance from multirotor c.o.m to 1st servo
dz = param.dz; % Z distance from multirotor c.o.m to 1st servo
l_1 = param.l_1; % 1st link length
l_2 = param.l_2; % 2nd link

% moment of inertia (MOI)
J_Bx = param.J_Bx; J_By = param.J_By; J_Bz = param.J_Bz;
J_S1x = param.J_S1x; J_S1y = param.J_S1y; J_S1z = param.J_S1z;
J_L1x = param.J_L1x; J_L1y = param.J_L1y; J_L1z = param.J_L1z;
J_S2x = param.J_S2x; J_S2y = param.J_S2y; J_S2z = param.J_S2z;
J_L2x = param.J_L2x; J_L2y = param.J_L2y; J_L2z = param.J_L2z;
J_S3x = param.J_S3x; J_S3y = param.J_S3y; J_S3z = param.J_S3z;
J_Ex = param.J_Ex; J_Ey = param.J_Ey; J_Ez = param.J_Ez;

% etc
g = param.g; % gravitational acceleration [m/s^2]

%% State distribution
p_x = q(1);
p_y = q(2);
p_z = q(3);
phi_x = q(4);
phi_y = q(5);
phi_z = q(6);
gma_1 = q(7);
gma_2 = q(8);

%%
t2 = cos(gma_1);
t3 = cos(phi_x);
t4 = cos(phi_y);
t5 = sin(gma_1);
t6 = sin(phi_x);
t7 = sin(phi_y);
t8 = gma_1+gma_2;
t9 = cos(t8);
t10 = l_1.*t2;
t11 = sin(t8);
t12 = l_1.*t5;
t13 = t2.*t7;
t16 = dy.*t3.*t4;
t18 = dy.*t6.*t7;
t20 = t3.*t4.*t5;
t14 = dz+t10;
t15 = l_2.*t9;
t17 = l_2.*t11;
t19 = t10./2.0;
t28 = t13+t20;
t21 = dz+t19;
t22 = t15./2.0;
t23 = t17./2.0;
t24 = t10+t15;
t25 = t12+t17;
t26 = t14+t15;
t27 = dx+t25;
t29 = t7.*t24;
t31 = t14+t22;
t32 = t3.*t4.*t25;
t33 = t3.*t7.*t26;
t34 = t4.*t6.*t26;
t30 = t4.*t27;
t35 = -t34;
t37 = t29+t32;
t36 = t16+t35;
t38 = t18+t30+t33;
G = [0.0;0.0;g.*(m_B+m_E+m_L1+m_L2+m_S1+m_S2+m_S3);g.*m_E.*t36+g.*m_S3.*t36+g.*m_S1.*(t16-dz.*t4.*t6)+g.*m_L1.*(t16-t4.*t6.*t21)+g.*m_L2.*(t16-t4.*t6.*t31)+g.*m_S2.*(t16-t4.*t6.*t14);-g.*m_L1.*(t18+t4.*(dx+t12./2.0)+t3.*t7.*t21)-g.*m_L2.*(t18+t4.*(dx+t12+t23)+t3.*t7.*t31)-g.*m_E.*t38-g.*m_S3.*t38-g.*m_S2.*(t18+t4.*(dx+t12)+t3.*t7.*t14)-g.*m_S1.*(t18+dx.*t4+dz.*t3.*t7);0.0;-g.*m_L2.*(t7.*(t10+t22)+t3.*t4.*(t12+t23))-g.*m_E.*t37-g.*m_S3.*t37-(g.*l_1.*m_L1.*t28)./2.0-g.*l_1.*m_S2.*t28;g.*l_2.*(t7.*t9+t3.*t4.*t11).*(m_E.*2.0+m_L2+m_S3.*2.0).*(-1.0./2.0)];
