function J_tau = getJ_tau(param, q)
%J_TAU
%    J_TAU = J_TAU(PHI_X,PHI_Y,PHI_Z)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-May-2021 21:24:31
%% Parameters
% masses
m_B = param.m_B; % multirotor body
m_S1 = param.m_S1; % 1st servo motor (XW540)
m_L1 = param.m_L1; % 1st link
m_S2 = param.m_S2; % 2nd servo motor (XH430)
m_L2 = param.m_L2; % 2nd link
m_S3 = param.m_S3; % 3rd servo motor (XL430-W250-T)
m_E = param.m_E; % end-effector (gripper)

% length
dx = param.dx; % X distance from multirotor c.o.m to 1st servo
dy = param.dy; % Y distance from multirotor c.o.m to 1st servo
dz = param.dz; % Z distance from multirotor c.o.m to 1st servo
l_1 = param.l_1; % 1st link length
l_2 = param.l_2; % 2nd link

% moment of inertia (MOI)
J_Bx = param.J_Bx; J_By = param.J_By; J_Bz = param.J_Bz;
J_S1x = param.J_S1x; J_S1y = param.J_S1y; J_S1z = param.J_S1z;
J_L1x = param.J_L1x; J_L1y = param.J_L1y; J_L1z = param.J_L1z;
J_S2x = param.J_S2x; J_S2y = param.J_S2y; J_S2z = param.J_S2z;
J_L2x = param.J_L2x; J_L2y = param.J_L2y; J_L2z = param.J_L2z;
J_S3x = param.J_S3x; J_S3y = param.J_S3y; J_S3z = param.J_S3z;
J_Ex = param.J_Ex; J_Ey = param.J_Ey; J_Ez = param.J_Ez;

% etc
g = param.g; % gravitational acceleration [m/s^2]

%% State distribution
p_x = q(1);
p_y = q(2);
p_z = q(3);
phi_x = q(4);
phi_y = q(5);
phi_z = q(6);
gma_1 = q(7);
gma_2 = q(8);

%%
t2 = cos(phi_x);
t3 = cos(phi_y);
t4 = cos(phi_z);
t5 = sin(phi_x);
t6 = sin(phi_y);
t7 = sin(phi_z);
t8 = t2.*t3;
J_tau = reshape([t5.*t7+t2.*t4.*t6,0.0,0.0,0.0,0.0,0.0,-t4.*t5+t2.*t6.*t7,0.0,0.0,0.0,0.0,0.0,t8,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,-t5,0.0,0.0,0.0,t6,t3.*t5,t8,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,8]);
